service: docker-selenium-lambda

provider:
  name: aws
  ecr:
    images:
      img_selenium:
        path: ./
        platform: linux/amd64

functions:
  scrap:
    timeout: 300
    memorySize: 2048
    image:
      name: img_selenium